version: '2'
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/notebooks
      - $PWD/images:/images
    ports:
      - 8888:8888 
  server:
    build: .
    command: ["pytest test_melanoma.py"]
    build: .
    volumes:
      - $PWD:/notebooks
      - $PWD/images:/images
    ports:
      - 8000:8000
    environment:
      - FLASK_DEBUG=1
    command: bash -c ["flask", "run", "--port=8000", "--host=0.0.0.0"]
